all : ../Figures/FSC_5000_10x_Low_Ref.png \
	  ../Figures/FSC_40000_10x_Low_Ref.png \
	  ../Figures/FSC_5000_10x_High_Ref.png \
	  ../Figures/FSC_5000_20x_High_Ref.png \
	  ../Figures/FSC_ProjReco_2016-09-05_02.png \
	  ../Figures/FSC_ProjReco_2016-09-09_01.png \
	  ../Figures/FSC_ProjReco_2016-09-13_01.png \
	  ../Figures/FSC_ProjReco_2016-09-13_04.png \
	  ../Figures/FSC_ProjReco_2016-09-13_05.png \
	  ../Figures/FSC_ProjReco_2016-09-13_06.png \
	  ../Figures/FSC_ProjReco_2016-09-14_01.png \
	  ../Figures/FSC_ProjReco_2016-09-20_01.png \
	  ../Figures/FSC_ProjReco_2016-09-20_03.png \
	  ../Figures/FSC_ProjReco_2016-09-20_05.png

../Figures/FSC_5000_10x_Low_Ref.png : FSC.py ../Data/FSC_5000_10x_Low_Ref.txt
	python FSC.py ../Data/FSC_5000_10x_Low_Ref.txt

../Figures/FSC_40000_10x_Low_Ref.png : FSC.py ../Data/FSC_40000_10x_Low_Ref.txt
	python FSC.py ../Data/FSC_40000_10x_Low_Ref.txt

../Figures/FSC_5000_10x_High_Ref.png : FSC.py ../Data/FSC_5000_10x_High_Ref.txt
	python FSC.py ../Data/FSC_5000_10x_High_Ref.txt

../Figures/FSC_5000_20x_High_Ref.png : FSC.py ../Data/FSC_5000_20x_High_Ref.txt
	python FSC.py ../Data/FSC_5000_20x_High_Ref.txt

../Figures/FSC_ProjReco_2016-09-05_02.png : FSC.py ../Data/FSC_ProjReco_2016-09-05_02.txt
	python FSC.py ../Data/FSC_ProjReco_2016-09-05_02.txt

../Figures/FSC_ProjReco_2016-09-09_01.png : FSC.py ../Data/FSC_ProjReco_2016-09-09_01.txt
	python FSC.py ../Data/FSC_ProjReco_2016-09-09_01.txt

../Figures/FSC_ProjReco_2016-09-13_01.png : FSC.py ../Data/FSC_ProjReco_2016-09-13_01.txt
	python FSC.py ../Data/FSC_ProjReco_2016-09-13_01.txt

../Figures/FSC_ProjReco_2016-09-13_04.png : FSC.py ../Data/FSC_ProjReco_2016-09-13_04.txt
	python FSC.py ../Data/FSC_ProjReco_2016-09-13_04.txt

../Figures/FSC_ProjReco_2016-09-13_05.png : FSC.py ../Data/FSC_ProjReco_2016-09-13_05.txt
	python FSC.py ../Data/FSC_ProjReco_2016-09-13_05.txt

../Figures/FSC_ProjReco_2016-09-13_06.png : FSC.py ../Data/FSC_ProjReco_2016-09-13_06.txt
	python FSC.py ../Data/FSC_ProjReco_2016-09-13_06.txt

../Figures/FSC_ProjReco_2016-09-14_01.png : FSC.py ../Data/FSC_ProjReco_2016-09-14_01.txt
	python FSC.py ../Data/FSC_ProjReco_2016-09-14_01.txt

../Figures/FSC_ProjReco_2016-09-20_01.png : FSC.py ../Data/FSC_ProjReco_2016-09-20_01.txt
	python FSC.py ../Data/FSC_ProjReco_2016-09-20_01.txt

../Figures/FSC_ProjReco_2016-09-20_03.png : FSC.py ../Data/FSC_ProjReco_2016-09-20_03.txt
	python FSC.py ../Data/FSC_ProjReco_2016-09-20_03.txt

../Figures/FSC_ProjReco_2016-09-20_05.png : FSC.py ../Data/FSC_ProjReco_2016-09-20_05.txt
	python FSC.py ../Data/FSC_ProjReco_2016-09-20_05.txt

clean :
	rm ../Figures/*.png
