all : C1 C2 C5 C6 CI CS C2V C5V C2H C5H S4 S10 \
	  D2 D5 D2V D5V D2H D5H T TD TH O OH

C1:
	python Symmetry_Plot.py ../Data/C1.txt

C2:
	python Symmetry_Plot_Y_Depth.py ../Data/C2.txt

C5:
	python Symmetry_Plot_Y_Depth.py ../Data/C5.txt

C6:
	python Symmetry_Plot_Y_Depth.py ../Data/C6.txt

CI:
	python Symmetry_Plot_Z_Depth.py ../Data/CI.txt

CS:
	python Symmetry_Plot_Z_Depth.py ../Data/CS.txt

C2V:
	python Symmetry_Plot_Y_Depth.py ../Data/C2V.txt

C5V:
	python Symmetry_Plot_Y_Depth.py ../Data/C5V.txt

C2H:
	python Symmetry_Plot_Z_Depth.py ../Data/C2H.txt

C5H:
	python Symmetry_Plot_Z_Depth.py ../Data/C5H.txt

S4:
	python Symmetry_Plot_Z_Depth.py ../Data/S4.txt

S10:
	python Symmetry_Plot_Z_Depth.py ../Data/S10.txt

D2:
	python Symmetry_Plot_Z_Depth.py ../Data/D2.txt

D5:
	python Symmetry_Plot_Z_Depth.py ../Data/D5.txt

D2V:
	python Symmetry_Plot_Z_Depth.py ../Data/D2V.txt

D5V:
	python Symmetry_Plot_Z_Depth.py ../Data/D5V.txt

D2H:
	python Symmetry_Plot_Z_Depth.py ../Data/D2H.txt

D5H:
	python Symmetry_Plot_Z_Depth.py ../Data/D5H.txt

T:
	python Symmetry_Plot.py ../Data/T.txt

TD:
	python Symmetry_Plot.py ../Data/TD.txt

TH:
	python Symmetry_Plot.py ../Data/TH.txt

O:
	python Symmetry_Plot.py ../Data/O.txt

OH:
	python Symmetry_Plot.py ../Data/OH.txt

clean:
	rm ../Figures/*.png
