all : C2 C6 CI CS C2V C2H S4 D2 D2V D2H T TD TH O OH

C2:
	python Symmetry_Plot_Y_Depth.py ../Data/C2.txt

C6:
	python Symmetry_Plot_Y_Depth.py ../Data/C6.txt

CI:
	python Symmetry_Plot_Z_Depth.py ../Data/CI.txt

CS:
	python Symmetry_Plot_Z_Depth.py ../Data/CS.txt

C2V:
	python Symmetry_Plot_Y_Depth.py ../Data/C2V.txt

C2H:
	python Symmetry_Plot_Z_Depth.py ../Data/C2H.txt

S4:
	python Symmetry_Plot_Z_Depth.py ../Data/S4.txt

D2:
	python Symmetry_Plot_Z_Depth.py ../Data/D2.txt

D2V:
	python Symmetry_Plot_Z_Depth.py ../Data/D2V.txt

D2H:
	python Symmetry_Plot_Z_Depth.py ../Data/D2H.txt

T:
	python Symmetry_Plot.py ../Data/T.txt

TD:
	python Symmetry_Plot.py ../Data/TD.txt

TH:
	python Symmetry_Plot.py ../Data/TH.txt

O:
	python Symmetry_Plot.py ../Data/O.txt

OH:
	python Symmetry_Plot.py ../Data/OH.txt

clean:
	rm ../Figures/*.png
