.PHONY: C2 C6 CI CS

all : C2 C6 CI

C2:
	python Symmetry_Plot_Y_Depth.py ../Data/C2.txt

C6:
	python Symmetry_Plot_Y_Depth.py ../Data/C6.txt

CI:
	python Symmetry_Plot_Z_Depth.py ../Data/CI.txt

CS:
	python Symmetry_Plot_Z_Depth.py ../Data/CS.txt

clean:
	rm ../Figures/*.png
